---
title: "Soil-to-atmosphere C02 Flux Data Processing"
author: "Natanel Ha"
date: "7/1/2021"
output: html_document
---

### Importing Libraries
```{r importing, message=FALSE, warning=FALSE}
library(tidyr)
library(dplyr)
library(ggplot2)
```

### Reading Datasets
```{r reading, message=FALSE, warning=FALSE}
collar_map <- readr::read_csv("collar_map.csv")
fluxes <- readr::read_csv("fluxes.csv")
```

### Select treatment and collar from collar_map 
```{r select, message=FALSE, warning=FALSE}
collar_map %>%
  select(Treatment, Collar)->
  treatment 
```

### Creating a long data table from fluxes and collar_map
```{r merge, message=FALSE, warning=FALSE}
fluxes %>%
  pivot_longer(-Collar, names_to="Date") %>% #Wide to Long
  filter(!is.na(value))%>%                   #Filter out NA
  left_join(treatment, by="Collar")->        #Merging 
  fluxes_merged
```

### Compute and Print Summary
```{r summary}
fluxes_merged %>%
  group_by(Treatment) %>%
  summarise(mean = mean(value), N = n(), Std_dev = sd(value))%>% 
  print()
```

### Boxplot with overlaid dots
```{r boxplot}
fluxes_merged %>%
  ggplot(aes(x = Treatment, y = value))+
  geom_boxplot()+
  geom_jitter(alpha = 0.4, aes(color = Date))+
  ggtitle("Soil-to-atmosphere CO2 flux Boxplot by treatment")+
  ylab("Soil-to-atmosphere CO2 Flux (µmol/m2/s)")+
  theme_minimal()
```

### Line Graph with error bars
```{r linegraph, message=FALSE, warning=FALSE}
fluxes_merged %>%
  group_by(Treatment, Date) %>%
  summarise(mean = mean(value), Std_dev = sd(value)) %>%
  ggplot(aes(x = Date, y = mean, color = Treatment, group = Treatment))+
  geom_line()+ 
  geom_errorbar(aes(ymax = mean + Std_dev, 
                    ymin = mean - Std_dev), 
                    width = 0.2, 
                    alpha = 0.4)+
  ggtitle("Soil-to-atmosphere CO2 Flux Line Graph with Error bars")+
  ylab("Mean Soil-to-atmosphere CO2 Flux (µmol/m2/s)")+
  theme_minimal()
```


### Finding out which collars do not appear in fluxes and printing 
```{r antijoin}
collar_map %>%
  anti_join(fluxes, by="Collar")
```

```{r print, echo=FALSE}
print("Collar 34 is listed in the metadata that do not appear in the fluxes data file.")
print("Collar 34 is in the Fresh Plot, in Group 9, and the treatment was Disturbance")  
```   

Session Info: 
```{r sessionInfo, echo=FALSE}
sessionInfo()
```
