---
title: "Creating Negative Emissions Scenarions"
author: "Natanel Ha"
date: "8/4/2021"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: 
     collapsed: false
     smooth_scroll: true
    theme: paper 
---

This document reflects done the work done by Natanel Ha on creating negative
emissions scenarios with Jay Fuhrman's Data

##### Importing Libraries 
```{r importing, message=FALSE, warning=FALSE}
library(hector)
library(ggplot2)
library(dplyr)
library(tidyr)
library(zoo)
```

## Converting Jay Fuhrman's Data
```{r convert, eval=FALSE, results='hide'}
# Reading in the csv
path <- "/Users/Natanel Ha/Documents/GitHub/Ha-Hector-Internship/"
data <- readr::read_csv(paste(path,
  "GCAM scenario data/GCAM-DAC-SSP3pctHR.csv",
  sep = ""
))
# setting scenario
scenario <- "SSP5-1p9-DACCS-3pctHR"

# Filtering data
data %>%
  filter(Region == "World") %>%
  filter(Variable == "Emissions|CO2|Energy and Industrial Processes" |
    Variable == "Emissions|CO2|AFOLU" |
    Variable == "Carbon Sequestration|Direct Air Capture") %>%
  filter(Scenario == scenario) %>%
  select(-Model, -Unit, -Scenario, -Region) ->
data

# Wide to long and column changing
data %>%
  pivot_longer(-Variable, names_to = "Years") ->
data

# Converting to Int
data$Years <- as.integer(data$Years)

# Filling in blank years
data %>%
  complete(Variable, Years = 2005:2100) %>%
  pivot_wider(names_from = Variable) %>%
  rename(ffi_emissions_with_negative = "Emissions|CO2|Energy and Industrial Processes") %>%
  rename(luc_emissions = "Emissions|CO2|AFOLU") %>%
  rename(daccs_uptake = "Carbon Sequestration|Direct Air Capture") ->
data

data$ffi_emissions_with_negative <- na.approx(data$ffi_emissions_with_negative, data$Years) / 3670

data$luc_emissions <- na.approx(data$luc_emissions, data$Years) / 3670

data$daccs_uptake <- na.approx(data$daccs_uptake, data$Years) / 3670

data %>%
  mutate(ffi_emissions = ffi_emissions_with_negative + daccs_uptake) %>%
  select(Years, ffi_emissions, daccs_uptake, luc_emissions) ->
data

write.csv(data, paste(path, "New Scenarios/", scenario, ".csv", sep = ""), row.names = FALSE)
```

## Plotting the Negative Scenarios
```{r rcp26jay, message=FALSE, warning=FALSE, results='hide'}
#Set Theme
theme_set(theme_minimal())

## Basic Run
#Configuring INI File
ini_file_norm <- system.file("input", "hector_rcp26.ini", package = "hector")
path <- "/Users/Natanel Ha/Documents/GitHub/Ha-Hector-Internship/New Scenarios/"

#This gets changed to reflect RCP 2.6 or RCP 1.9
ini_file_SSP1 <- paste(path, "jay_SSP1.ini", sep="")
ini_file_SSP2 <- paste(path, "jay_SSP2.ini", sep="")
ini_file_SSP4 <- paste(path, "jay_SSP4.ini", sep="")
ini_file_SSP5 <- paste(path, "jay_SSP5.ini", sep="")

#Initialize a Hector Instance for each file
coreNorm <- newcore(ini_file_norm)
coreSSP1 <- newcore(ini_file_SSP1)
coreSSP2 <- newcore(ini_file_SSP2)
coreSSP4 <- newcore(ini_file_SSP4)
coreSSP5 <- newcore(ini_file_SSP5)

#Run the Cores
run(coreNorm) 
run(coreSSP1)
run(coreSSP2)
run(coreSSP4)
run(coreSSP5)

#Retrieve Results
resultsNorm <- fetchvars(coreNorm, 2005:2100, scenario = "Hector 2.6")
resultsSSP1 <- fetchvars(coreSSP1, 2005:2100, scenario = "SSP1")
resultsSSP2 <- fetchvars(coreSSP2, 2005:2100, scenario = "SSP2")
resultsSSP4 <- fetchvars(coreSSP4, 2005:2100, scenario = "SSP4")
resultsSSP5 <- fetchvars(coreSSP5, 2005:2100, scenario = "SSP5")

#Retrieve fluxes Results 
result_vars <- c(OCEAN_CFLUX(), LAND_CFLUX(), FFI_EMISSIONS(), DACCS_UPTAKE())
resultsNormFlux <- fetchvars(coreNorm, 2005:2100, result_vars, scenario = "Hector 2.6")
resultsSSP1Flux <- fetchvars(coreSSP1, 2005:2100, result_vars, scenario = "SSP1")
resultsSSP2Flux <- fetchvars(coreSSP2, 2005:2100, result_vars, scenario = "SSP2")
resultsSSP4Flux <- fetchvars(coreSSP4, 2005:2100, result_vars, scenario = "SSP4")
resultsSSP5Flux <- fetchvars(coreSSP5, 2005:2100, result_vars, scenario = "SSP5")


#Combining into one dataset 
results <- rbind(resultsNorm, resultsSSP1, resultsSSP2,
                 resultsSSP4, resultsSSP5)
resultsFlux <- rbind(resultsNormFlux, resultsSSP1Flux, resultsSSP2Flux, 
                     resultsSSP4Flux, resultsSSP5Flux)

#Calculating Atmospheric flux 
resultsFlux %>%
  select(-units) %>%
  pivot_wider(names_from = variable) %>%
  mutate(atmosphere_flux = (ffi_emissions - daccs_uptake - atm_ocean_flux - atm_land_flux))%>%
  select(-ffi_emissions, -daccs_uptake) %>%
  pivot_longer(3:5, names_to = "variable")->
  resultsFlux

##Line Graph
lineGraphCompare <- ggplot(results)+
  aes(x = year, y = value, color = scenario) +
  geom_line() +
  facet_wrap(~variable, scales = "free_y", 
             labeller = labeller(variable = c("Ca" = "CO2 Concentration (ppmv CO2)",
                                              "Ftot" = "Total Radiative Forcing (W/m2)",
                                              "FCO2" = "CO2 Forcing (W/m2)",
                                              "Tgav" = "Global Mean Temperature (degrees C)")))+
  ylab(NULL)+
  guides(color = guide_legend(title = "Scenario"))+
  scale_color_viridis_d()+
  xlab("Year")


##Plotting Fluxes
#Faceted
fluxFacetLineCompare <- ggplot(resultsFlux)+
  aes(x = year, y = value, color = scenario) +
  geom_line() +
  facet_wrap(~variable, scales = "free_y",
             labeller = labeller(variable = c("atm_land_flux" = "Land Net Flux",
                                              "atm_ocean_flux" = "Ocean Net Flux",
                                              "atmosphere_flux" = "Atmosphere Net Flux")))+
  ylab("Carbon Flux(Pg C/yr)")+
  scale_color_viridis_d()+
  xlab("Year")
```

### Plots {.tabset} 
#### RCP 2.6
```{r rcp26jayPlots, echo=FALSE}
lineGraphCompare
fluxFacetLineCompare
```

#### RCP 1.9
```{r rcp19jay, include=FALSE}
ini_file_SSP1 <- paste(path, "jay_19_SSP1.ini", sep="")
ini_file_SSP2 <- paste(path, "jay_19_SSP2.ini", sep="")
ini_file_SSP4 <- paste(path, "jay_19_SSP4.ini", sep="")
ini_file_SSP5 <- paste(path, "jay_19_SSP5.ini", sep="")

#Initialize a Hector Instance for each file
coreNorm <- newcore(ini_file_norm)
coreSSP1 <- newcore(ini_file_SSP1)
coreSSP2 <- newcore(ini_file_SSP2)
coreSSP4 <- newcore(ini_file_SSP4)
coreSSP5 <- newcore(ini_file_SSP5)

#Run the Cores
run(coreNorm) 
run(coreSSP1)
run(coreSSP2)
run(coreSSP4)
run(coreSSP5)

#Retrieve Results
resultsNorm <- fetchvars(coreNorm, 2005:2100, scenario = "Hector 2.6")
resultsSSP1 <- fetchvars(coreSSP1, 2005:2100, scenario = "SSP1")
resultsSSP2 <- fetchvars(coreSSP2, 2005:2100, scenario = "SSP2")
resultsSSP4 <- fetchvars(coreSSP4, 2005:2100, scenario = "SSP4")
resultsSSP5 <- fetchvars(coreSSP5, 2005:2100, scenario = "SSP5")

#Retrieve fluxes Results 
result_vars <- c(OCEAN_CFLUX(), LAND_CFLUX(), FFI_EMISSIONS(), DACCS_UPTAKE())
resultsNormFlux <- fetchvars(coreNorm, 2005:2100, result_vars, scenario = "Hector 2.6")
resultsSSP1Flux <- fetchvars(coreSSP1, 2005:2100, result_vars, scenario = "SSP1")
resultsSSP2Flux <- fetchvars(coreSSP2, 2005:2100, result_vars, scenario = "SSP2")
resultsSSP4Flux <- fetchvars(coreSSP4, 2005:2100, result_vars, scenario = "SSP4")
resultsSSP5Flux <- fetchvars(coreSSP5, 2005:2100, result_vars, scenario = "SSP5")


#Combining into one dataset 
results <- rbind(resultsNorm, resultsSSP1, resultsSSP2,
                 resultsSSP4, resultsSSP5)
resultsFlux <- rbind(resultsNormFlux, resultsSSP1Flux, resultsSSP2Flux, 
                     resultsSSP4Flux, resultsSSP5Flux)

#Calculating Atmospheric flux 
resultsFlux %>%
  select(-units) %>%
  pivot_wider(names_from = variable) %>%
  mutate(atmosphere_flux = (ffi_emissions - daccs_uptake - atm_ocean_flux - atm_land_flux))%>%
  select(-ffi_emissions, -daccs_uptake) %>%
  pivot_longer(3:5, names_to = "variable")->
  resultsFlux

##Line Graph
lineGraphCompare <- ggplot(results)+
  aes(x = year, y = value, color = scenario) +
  geom_line() +
  facet_wrap(~variable, scales = "free_y", 
             labeller = labeller(variable = c("Ca" = "CO2 Concentration (ppmv CO2)",
                                              "Ftot" = "Total Radiative Forcing (W/m2)",
                                              "FCO2" = "CO2 Forcing (W/m2)",
                                              "Tgav" = "Global Mean Temperature (degrees C)")))+
  ylab(NULL)+
  guides(color = guide_legend(title = "Scenario"))+
  scale_color_viridis_d()+
  xlab("Year")


##Plotting Fluxes
#Faceted
fluxFacetLineCompare <- ggplot(resultsFlux)+
  aes(x = year, y = value, color = scenario) +
  geom_line() +
  facet_wrap(~variable, scales = "free_y",
             labeller = labeller(variable = c("atm_land_flux" = "Land Net Flux",
                                              "atm_ocean_flux" = "Ocean Net Flux",
                                              "atmosphere_flux" = "Atmosphere Net Flux")))+
  ylab("Carbon Flux(Pg C/yr)")+
  scale_color_viridis_d()+
  xlab("Year")
```

```{r rcp19jayPlots, echo=FALSE}
lineGraphCompare
fluxFacetLineCompare
```


### Session Info: 
```{r sessionInfo, echo=FALSE}
sessionInfo()
```

<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>

